### ISSUE TITLE
Configuration file for preopened sockets

### ISSUE THREAD

**Issue by npmccallum** [enarx/enarx#1226]
Currently, our wasmldr sets up a wasm environment with access only to stdin/out. We need to have the ability to make network connections.

We intend for this mechanism to be temporary as we bring up a more robust environment configuration. However, this may form the basis of the environment setup. It should probably be specified as a configuration file, preferably `toml`. Here's an example of what that file might look like.

```toml
[[files]]
type = "stdin"

[[files]]
type = "stdout"

[[files]]
type = "stderr"

[[files]]
type = "listen"
port = 443

[[files]]
type = "connect"
addr = "google.com"
port = 443
```

# Acceptance Criteria:
- [ ] Documented configuration file format
- [ ] Implementation and tests provided
