### ISSUE TITLE
[Bug]: TLS "connect" socket I/O occasionally succeeds (and usually fails)

### ISSUE THREAD

**Issue by rvolosatovs** [enarx/enarx#2134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

Occasional
```
Caused by:
    Resource temporarily unavailable (os error 6)
Error: failed to execute default function
```

When using

```toml
[[files]]
name = "api.github.com"
kind = "connect"
prot = "tls"
port = 443
host = "api.github.com"
```

### Expected Behaviour

Consistent success

### Environment Information

enarx 0.6.3
