### ISSUE TITLE
Action(s) for publishing and deploying from Drawbridge

### ISSUE THREAD

**Issue by bstrie** [enarx/enarx#2390]
We eventually want a comprehensive end-to-end test of the complete Enarx flow. At the same time, we expect that users will want to have the ability to have their CI publish and deploy code to and from Drawbridge. We can implement a public Github Action that provides this ability, which we can then re-use for regularly-scheduled integration tests. The process of developing this test will also help guide us in finding the holes in our current deployment and attestation story.

The action will expect the user to pass in a Drawbridge user token (stored as a repository secret) and a path to a workload.

The action consists of two parts: publishing and deploying. It's unclear whether these should be exposed as separate actions.

First, focus on publishing. For the MVP, we should build Enarx from source (eventually we should default to installing a released version of Enarx, and make building from source optional). For the MVP, publish only to the Drawbridge staging instance (eventually this should be configurable). For the MVP, it should use a random/UUID/timestamp as a workload version in order to avoid collisions (eventually this should be configurable). For the MVP, don't pass in signing keys or workload digests (eventually this should be configurable). Once this is complete we will determine how the MVP should deploy and the parameters it will use (e.g. attestation and the selection of which machines to deploy to).

**Comment by rvolosatovs** [comment]
I am not sure we need a `deploy` action today, but we do need a `publish`, a step using it should look something like this:
```yml
- uses: enarx/publish@v1
  with:
	path: ./path/to/my/drawbridge/package # eventually we may want to assume a default path here, perhaps even have `enarx/package` action, which would take WASM files and `Enarx.toml` as input and output a valid Drawbridge package in that default path
	owner: examples
	name: fibonacci-c
	version: 0.1.0
	store: store.mymegacorp.com # optional, default to store.profian.com
	token: ${{ secrets.ENARX_PUBLISH_TOKEN }} # we may want to have a separate enarx/login action, but we should probably start with just one
```
See also
- https://github.com/docker/build-push-action
- https://github.com/tu6ge/publish-action
for inspiration

`enarx/publish` should also set `outputs` field https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
And IMO the outputs should be:
- `digest`
- `deploy-token` for private workloads

Once we have that, we could also have `enarx/deploy`, e.g.:
```yml
- uses: enarx/deploy@v1
  with:
	owner: examples
    name: fibonacci-c
    version: 0.1.0
	store: store.mymegacorp.com # optional, default to store.profian.com
    token: ${{ secrets.ENARX_DEPLOY_TOKEN }} # optional, none by default
    digest:
		sha256: DEADEEF # optional, defaults to none
    backend: nil # optional, if set, then it's an enum: `nil`, `kvm`, `sgx`, `sev`
```

Once we have more than 1 `enarx` action, we could think about defaulting to e.g. taking `owner` from `ENARX_OWNER` or `name` from `ENARX_NAME`
